#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

source $OPENSHIFT_REPO_DIR/misc/utils/virtualenv

# uwsgi has to be started first, or else nginx won't be able to connect to
# the unix socket (since it would not exist)
activate_virtualenv
nohup uwsgi $OPENSHIFT_DATA_DIR/uwsgi/uwsgi.ini &

nohup $OPENSHIFT_DATA_DIR/nginx/sbin/nginx &
