#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#exit 0

$OPENSHIFT_DATA_DIR/nginx/sbin/nginx -s stop

UWSGI_PIDFILE=$OPENSHIFT_DATA_DIR/uwsgi/uwsgi.pid
if [ -f $UWSGI_PIDFILE ]; then
	kill -QUIT $(cat $UWSGI_PIDFILE)
fi

exit 0
