#!/usr/bin/bash

export TERM=xterm-256color

function _base_message() {
	ECHO="echo -e"
	if [ $# -eq 3 ]; then
		if [ "x$2" = "x-n" ]; then
			ECHO="echo -ne"
		fi
		MSG=$3
	elif [ $# -eq 2 ]; then
		MSG=$2
	fi

	COLOR=$1
	color=$(tput setaf $COLOR)
	reset=$(tput sgr0)

	$ECHO "${color}$MSG${reset}"
}

function warning_message() {
	_base_message 1 "$@"
}

function info_message() {
	_base_message 4 "$@"
}

function success_message() {
	_base_message 2 "$@"
}
